export interface ProductTest {
    product_id: number,
    product_type: string,
    product_mark: string,
    product_status: string,
    product_description: string,
    product_processor: string,
    product_system: string,
    product_camera: string,
    product_disc_type: string,
    product_graphics_card: string,
    product_price: number,
    product_ram_size: number,
    product_disc_size: number,
    product_screen_diagonal: number,
    product_amount_available: number,
    product_amount_sold: number,
    product_camera_resolution: number,
    product_time_work: number,
    product_range: number
  }